runtime: go111

handlers:
- url: /hello
  script: auto

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static